#!/bin/sh /etc/rc.common
# Copyright (C) 2008 OpenWrt.org
# Updated 2022 6 21 DBICT composed by CCJ


USE_PROCD=1
START=24

start_service() {
    echo start_ffserver_service
    procd_open_instance
    procd_set_param command /usr/bin/ffserver -f /root/usbcam/ffserver.conf
    #procd_set_param command /usr/bin/ffserver -f /root/usbcam/ffserver1.conf
    procd_set_param respawn ${respawn_thrhold:-30} ${respawn_timeout:-5} ${respawn_retry:-10}
    procd_close_instance
}
